version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    cooldown:
      default-days: 14
    groups:
      prod-deps:
        dependency-type: production
      dev-deps:
        dependency-type: development
