[run]
command = "npm run dev"
name = "Start application"
onBoot = false

[run.environment]
PORT = "3000"

[nix]
channel = "stable-24_05"

[[ports]]
localPort = 5000
externalPort = 80

[[ports]]
localPort = 5001
externalPort = 3000